// Mocks generated by Mockito 5.1.0 from annotations
// in riverpod_sample/test/golden_test.dart.
// Do not manually edit this file.

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:riverpod_sample/view_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockViewModel extends _i1.Mock implements _i2.ViewModel {
  MockViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setRef(_i3.WidgetRef? ref) =>
      super.noSuchMethod(Invocation.method(#setRef, [ref]),
          returnValueForMissingStub: null);
  @override
  void onIncrease() => super.noSuchMethod(Invocation.method(#onIncrease, []),
      returnValueForMissingStub: null);
  @override
  void onDecrease() => super.noSuchMethod(Invocation.method(#onDecrease, []),
      returnValueForMissingStub: null);
  @override
  void onReset() => super.noSuchMethod(Invocation.method(#onReset, []),
      returnValueForMissingStub: null);
}
